name: Bug Report
description: Report a runtime, API, or compatibility defect.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide a minimal reproduction and include loader URL + commit/tag when possible.
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Element Factory
        - Theme/Styling
        - Config/Persistence
        - Loader/Bootstrap
        - Documentation
        - CI/Build
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / Commit / Tag
      placeholder: "example: main@abcdef1 or v2.1.0"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: Provide exact steps and sample code.
      placeholder: |
        1. Load ...
        2. Create ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste console output or attach images.
      render: shell
  - type: checkboxes
    id: checks
    attributes:
      label: Validation
      options:
        - label: I checked for duplicate issues.
          required: true
        - label: I can reproduce this on the latest main branch.
          required: true
