-- Rayfield bundle generator (100% Lua)
-- Usage: lua scripts/build-bundle.lua

local OUTPUT_CORE = "dist/rayfield-runtime-core.bundle.lua"
local OUTPUT_UI = "dist/rayfield-runtime-ui.bundle.lua"
local OUTPUT_BOOTSTRAP = "dist/rayfield-production.bootstrap.lua"

local ROOT_DEFAULT = "https://raw.githubusercontent.com/Ahlstarr-Mayjishan/Rayfield-mod/main/"

local EXTRA_PATHS = {
	"Main loader/rayfield-modified.lua",
	"Main loader/rayfield-all-in-one.lua",
	"feature/rayfield-all-in-one.lua"
}

local CORE_PREFIXES = {
	"src/api/",
	"src/core/",
	"src/entry/"
}

local CORE_EXACT = {
	["src/services/compatibility.lua"] = true,
	["src/services/logger.lua"] = true,
	["src/services/input-dispatcher.lua"] = true
}

local MODULE_MAP_PATH = "src/entry/module-map.lua"
local sortUnique

local function decodeUrlPath(value)
	if type(value) ~= "string" then
		return value
	end
	return (value:gsub("%%(%x%x)", function(hex)
		return string.char(tonumber(hex, 16))
	end))
end

local function readFile(path)
	local file, err = io.open(path, "rb")
	if not file then
		error("Failed to read " .. tostring(path) .. ": " .. tostring(err))
	end
	local data = file:read("*a")
	file:close()
	return data
end

local function writeFile(path, data)
	local file, err = io.open(path, "wb")
	if not file then
		error("Failed to write " .. tostring(path) .. ": " .. tostring(err))
	end
	file:write(data)
	file:close()
end

local function ensureDistFolder()
	local separator = package and package.config and package.config:sub(1, 1) or "\\"
	local command
	if separator == "\\" then
		command = "mkdir dist >nul 2>nul"
	else
		command = "mkdir -p dist"
	end
	pcall(os.execute, command)
end

local function listSrcLuaFiles()
	local command = "rg --files src -g \"*.lua\""
	local pipe = io.popen(command, "r")
	if not pipe then
		error("Failed to execute command: " .. command)
	end

	local files = {}
	for line in pipe:lines() do
		line = line:gsub("\\", "/")
		if #line > 0 then
			table.insert(files, line)
		end
	end
	pipe:close()
	table.sort(files)
	return files
end

local function listModuleMapPaths()
	local loadFileFn = loadfile
	if type(loadFileFn) ~= "function" then
		return {}
	end

	local chunk, err = loadFileFn(MODULE_MAP_PATH)
	if not chunk then
		error("Failed to load module map " .. MODULE_MAP_PATH .. ": " .. tostring(err))
	end

	local ok, moduleMap = pcall(chunk)
	if not ok or type(moduleMap) ~= "table" then
		error("Invalid module map from " .. MODULE_MAP_PATH)
	end

	local paths = {}
	for _, mapping in pairs(moduleMap) do
		if type(mapping) == "table" then
			for _, candidate in ipairs(mapping) do
				if type(candidate) == "string" and candidate:match("%.lua$") then
					table.insert(paths, (decodeUrlPath(candidate):gsub("\\", "/")))
				end
			end
		end
	end

	return sortUnique(paths)
end

local function startsWith(value, prefix)
	return value:sub(1, #prefix) == prefix
end

local function isCorePath(path)
	if CORE_EXACT[path] then
		return true
	end
	for _, prefix in ipairs(CORE_PREFIXES) do
		if startsWith(path, prefix) then
			return true
		end
	end
	return false
end

local function longQuote(value)
	local eqCount = 0
	while true do
		local marker = "]" .. string.rep("=", eqCount) .. "]"
		if not value:find(marker, 1, true) then
			break
		end
		eqCount = eqCount + 1
	end
	local eq = string.rep("=", eqCount)
	return "[" .. eq .. "[" .. value .. "]" .. eq .. "]"
end

sortUnique = function(paths)
	local seen = {}
	local out = {}
	for _, path in ipairs(paths) do
		if not seen[path] then
			seen[path] = true
			table.insert(out, path)
		end
	end
	table.sort(out)
	return out
end

local function buildBundleContent(bundleName, paths)
	local lines = {}
	table.insert(lines, "-- AUTO-GENERATED by scripts/build-bundle.lua")
	table.insert(lines, "local bundle = _G.__RAYFIELD_BUNDLE_SOURCES or {}")
	table.insert(lines, "_G.__RAYFIELD_BUNDLE_SOURCES = bundle")
	table.insert(lines, "_G.__RAYFIELD_BUNDLE_MODE = \"bundle_first\"")
	table.insert(lines, "")
	table.insert(lines, "local function put(path, source)")
	table.insert(lines, "\tbundle[path] = source")
	table.insert(lines, "end")
	table.insert(lines, "")
	table.insert(lines, "local BUNDLE_NAME = " .. string.format("%q", bundleName))
	table.insert(lines, "")

	for _, path in ipairs(paths) do
		local source = readFile(path)
		table.insert(lines, "put(" .. string.format("%q", path) .. ", " .. longQuote(source) .. ")")
	end

	table.insert(lines, "")
	table.insert(lines, "return {")
	table.insert(lines, "\tname = BUNDLE_NAME,")
	table.insert(lines, "\tcount = " .. tostring(#paths) .. ",")
	table.insert(lines, "\tbundle = bundle")
	table.insert(lines, "}")

	return table.concat(lines, "\n") .. "\n"
end

local function buildBootstrapContent()
	local lines = {}
	table.insert(lines, "-- AUTO-GENERATED by scripts/build-bundle.lua")
	table.insert(lines, "local ROOT = (_G and _G.__RAYFIELD_RUNTIME_ROOT_URL) or " .. string.format("%q", ROOT_DEFAULT))
	table.insert(lines, "_G.__RAYFIELD_RUNTIME_ROOT_URL = ROOT")
	table.insert(lines, "_G.__RAYFIELD_BUNDLE_MODE = \"bundle_first\"")
	table.insert(lines, "")
	table.insert(lines, "local compileString = loadstring or load")
	table.insert(lines, "if not compileString then")
	table.insert(lines, "\terror(\"No Lua compiler function available (loadstring/load)\")")
	table.insert(lines, "end")
	table.insert(lines, "")
	table.insert(lines, "local function compileChunk(source, label)")
	table.insert(lines, "\tif type(source) ~= \"string\" then")
	table.insert(lines, "\t\terror(\"Invalid Lua source for \" .. tostring(label) .. \": \" .. type(source))")
	table.insert(lines, "\tend")
	table.insert(lines, "\tsource = source:gsub(\"^\\239\\187\\191\", \"\")")
	table.insert(lines, "\tsource = source:gsub(\"^\\0+\", \"\")")
	table.insert(lines, "\tlocal chunk, err = compileString(source)")
	table.insert(lines, "\tif not chunk then")
	table.insert(lines, "\t\terror(\"Failed to compile \" .. tostring(label) .. \": \" .. tostring(err))")
	table.insert(lines, "\tend")
	table.insert(lines, "\treturn chunk")
	table.insert(lines, "end")
	table.insert(lines, "")
	table.insert(lines, "local function loadRemoteLua(path)")
	table.insert(lines, "\tlocal source = game:HttpGet(ROOT .. path)")
	table.insert(lines, "\treturn compileChunk(source, path)()")
	table.insert(lines, "end")
	table.insert(lines, "")
	table.insert(lines, "loadRemoteLua(\"dist/rayfield-runtime-core.bundle.lua\")")
	table.insert(lines, "loadRemoteLua(\"dist/rayfield-runtime-ui.bundle.lua\")")
	table.insert(lines, "")
	table.insert(lines, "local bundle = _G.__RAYFIELD_BUNDLE_SOURCES or {}")
	table.insert(lines, "local entrySource = bundle[\"Main loader/rayfield-modified.lua\"]")
	table.insert(lines, "if type(entrySource) ~= \"string\" then")
	table.insert(lines, "\tentrySource = game:HttpGet(ROOT .. \"Main%20loader/rayfield-modified.lua\")")
	table.insert(lines, "end")
	table.insert(lines, "return compileChunk(entrySource, \"Main loader/rayfield-modified.lua\")()")
	return table.concat(lines, "\n") .. "\n"
end

local function build()
	ensureDistFolder()

	local srcFiles = listSrcLuaFiles()
	local moduleMapPaths = listModuleMapPaths()
	local corePaths = {}
	local uiPaths = {}

	for _, path in ipairs(srcFiles) do
		if isCorePath(path) then
			table.insert(corePaths, path)
		else
			table.insert(uiPaths, path)
		end
	end

	for _, path in ipairs(moduleMapPaths) do
		if isCorePath(path) then
			table.insert(corePaths, path)
		else
			table.insert(uiPaths, path)
		end
	end

	for _, extraPath in ipairs(EXTRA_PATHS) do
		table.insert(corePaths, extraPath)
	end

	corePaths = sortUnique(corePaths)
	uiPaths = sortUnique(uiPaths)

	writeFile(OUTPUT_CORE, buildBundleContent("rayfield-runtime-core", corePaths))
	writeFile(OUTPUT_UI, buildBundleContent("rayfield-runtime-ui", uiPaths))
	writeFile(OUTPUT_BOOTSTRAP, buildBootstrapContent())

	print(string.format("Wrote %s (%d modules)", OUTPUT_CORE, #corePaths))
	print(string.format("Wrote %s (%d modules)", OUTPUT_UI, #uiPaths))
	print(string.format("Wrote %s", OUTPUT_BOOTSTRAP))
end

build()
